### ISSUE TITLE
Call a method?

### ISSUE THREAD

**Issue by chrismbeckett** [eavichay/showroom#6]
Just starting to develop tests for my native web components and really love this project. The only thing I can't figure out from the samples is how do you call a method on a web component and return the value to my test?

**Comment by eavichay** [comment]
Hey, sorry for late response... 
you can define methods from the descriptor file (add "methods" section):
```js
export default {
  component,
  methods: {
    someName: () => showroom.component.doSomething(arg1, arg2, ...),
    someOtherName: () => showroom.component.doSomethingElse(),
    ...
  }
}
```

If you want to trigger via puppeteer simply `await showroom.trigger('someName')`
Prepare your actions in the descriptor and they are also accessible via the UI.

Hope this helps.

**Comment by chrismbeckett** [comment]
Thank you for the reply. Unfortunately, it doesn't seem to be working.

```js
export default {
	component: 'an-element',
	alias: '<an-element>',
	path: '/.build/an-element.mjs',
	autoAttributes: true,
	autoProperties: true,
	properties: {
		'clickCount': 0
	},
	events: ['clickcountchanged'],
	functions: {
		click: () => showroom.component.click()
	},
	methods: {
		isReady: () => showroom.component.isReady()
	},
	innerHTML: `
    Click Me
  `
};
```

```js
	it('should be ready', async () => {
		const isReady = await showroom.trigger('isReady');
		const ready = await showroom.getProperty('ready');
		console.log('ready', isReady, ready);
		assert.equal(ready, true);
	});
```

**Comment by chrismbeckett** [comment]
Also, what do the `autoProperties` and `autoAttributes` keys do? I have been trying to figure out how to use this too by just looking at the examples.

**Comment by chrismbeckett** [comment]
Is there anyway to just a direct element handle to my web component in my test script?

**Comment by chrismbeckett** [comment]
I think the problem may be with your trigger function? I don't see that it returns anything?

```js
  async trigger (fnName) {
    await this.page.evaluate((fnName) => {
      // @ts-ignore
      dashboard.trigger(fnName);
    }, fnName);
  }
```

**Comment by chrismbeckett** [comment]
Sorry, I am new to using Puppeteer. After digging through your code more, studying the Puppeteer API, finding the page reference, and then experimenting directly with `page.evaluate`, it seems there are some issues with Puppeteer with regard to invoking methods on elements. Despite being able to manually invoke a method that returns a promise through the browser, I was unable to invoke it correctly in Puppeteer.

**Comment by eavichay** [comment]
This is correct, it is not meant for calculations. You can, however run the function and get the results using puppeteer.

```js
it('should do something', async () => {
  const result = await page.evaluate((param) => {
    return showroom.component.computeSomething(param);
  }, someValueForParameter);
  console.log(result);
}
```
